--create user etl WITH PASSWORD 'demopass';

GRANT CONNECT ON DATABASE "ETL" to etl;

GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public To etl;

GRANT USAGE ON SCHEMA public To etl;

GRANT CREATE ON SCHEMA public To etl;

GRANT ALL PRIVILEGES ON SCHEMA public TO etl;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO etl;

