use [master]
GO
CREATE LOGIN [etl] WITH PASSWORD=N'demopass',DEFAULT_DATABASE=[ADF],CHECK_EXPIRATION=OFF,CHECK_POLICY=OFF
GO
USE [ADF]
GO
CREATE USER [etl] FOR LOGIN [etl]
GO
USE [ADF]
GO
ALTER ROLE [db_datareader] ADD MEMBER [etl]
GO
use [master]
GO
GRANT CONNECT SQL TO [etl]
GO


